services:
  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - http.port=9200
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=adm-Password0
    ports:
      - '9200:9200'
      - '9600:9600'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -ku admin:adm-Password0 https://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"
        ]
      interval: 5s
      timeout: 5s
      retries: 24
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    volumes:
      - ./volumes/keycloak/import:/opt/keycloak/data/import
    environment:
      KEYCLOAK_USER: dima
      KEYCLOAK_PASSWORD: dima
      KC_BOOTSTRAP_ADMIN_USERNAME: dimaAdmin
      KC_BOOTSTRAP_ADMIN_PASSWORD: dimaAdmin
      KEYCLOAK_IMPORT: "/tmp/realm-export.json"
      KC_HEALTH_ENABLED: "true"
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'HEAD /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3;cat <&3"]
      interval: 10s
      timeout: 5s
      retries: 15
    command:
      - start-dev
      - --import-realm
      - --hostname-strict
      - "false"
      - --hostname
      - "http://localhost:8080/"
      - --proxy-headers
      - forwarded
      - --hostname-backchannel-dynamic
      - "true"

volumes:
  opensearch-data: